### ISSUE TITLE
highlight()

### ISSUE THREAD

**Issue by erikrose** [erikrose/oedipus#5]
Implement excerpting (or, in ElasticSearch parlance, highlighting). Design a way to do this compatibly for both ES and Sphinx, as it's not implemented at all in elasticutils yet.

Maybe this makes sense as a chainable method on `S`; maybe not. Use your neurons. :-)

**Comment by willkg** [comment]
I'll grab this one for now.  If it turns out to be too scary and I'm not paralyzed with fright, I'll unassign myself or ask Erik for the h3lp5.

**Comment by willkg** [comment]
Talked with Erik about life and all that.

Rough notes:
- Elastic Search highlight: http://www.elasticsearch.org/guide/reference/api/search/highlighting.html
- Sphinx API has BuildExcerpt, but there's an excerpt method in search.clients.SearchClient that's worth looking at (albeit briefly)

Looks like making highlight a chainable part of S is a good idea.  Depending on what the result set looks like, it's probably the case that it's better to add the highlighted version as an additional attribute from the model instance in the result set.  Otherwise the API feels awkward (modifying the document string, returning an additional list of highlighted bits as an attribute of the result set, having a separate dict of document id -> highlighted version, ...).

I want to take another gander at ElasticUtils and figure out how it's going to be implemented there and what the ramifications of highlight taking a query instead of a result set are.

**Comment by erikrose** [comment]
Just ran across some old design sketches for this, which I'll paste in case they help inspire you. Consider this a basket of things to not forget, not anything to constrain you:

```
* Excerpts. Maybe ....filter(what=ever).excerpting(some_field=(150, 3)). But where to put pre_tags, post_tags, tags_schema, order?

    # This is the usual form, which relies on defaults set in the SearchModel
    # or someplace:
    excerpting('some', 'fields')

    # Or you can be explicit:    
    excerpting(field('some', order='score', pre_tags=['<smoo>']), field(...), ...)
    # "field" name is up for grabs.

    See http://www.elasticsearch.org/guide/reference/api/search/highlighting.html for ElasticSearch's API.
* Maybe be able to set default excerpt sizes etc. on SearchModels or even their individual fields.
```

**Comment by willkg** [comment]
f0f4fd71e0401ebbe543a4af2dd583c3d85ea115
